# -*- coding: utf-8 -*-
"""Semana02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diEjrMIJQ68cLRX69P3Ew5KfrTdtEFx7
"""

print('hola mundo como estas' + ' ' +'7.7')

"""#tipos de datos"""

from typing import TextIO
entero = 12
nombre = 'isabela'
estatura = 1.74
estudiante = True
dato_complejo = 3+2j
nulo = None
print(type(entero))
print(type(nombre))
print(type(estatura))
print(type(estudiante))
print(type(dato_complejo))
print(type(nulo))

segundo_nombre,edad, tiene_hambre, estatura = "Isabela",18,True,1.74
print(segundo_nombre,edad,tiene_hambre,estatura)



user = 'Maria'
user2 = 'isa'

texto = 'esto es un texto de varias lineas\
ya tu sabes como es la vaina'
print(user)
print(user2)
print(texto)

"""#ejemplos

"""

librox = 'esto es un libro muy interesante\
ya tu sabes como es la vaina'
print(librox)
holi = 'hola como te encuentras /t espero que bien '
print(holi)

"""#comentarios

"""

#este es un comentario de una sola linea
'''este es un comentario
de varias
 lineas'''

'''def saludar():
  print('hola')
  return saludar()'''#tambien sirve para desactivar el codigo identacion es el espacio al inicio

"""#docstrings("")

"""

a = 5
b = 8

def sumar( a, b):

  """
Esta funcion recibe dos numeros como parametros y
 Suma dos numeros y devuelve el resultado.

"""
  return a + b


print(sumar._doc_)

"""#concatenar strings

"""

print('Hola '+ user + " como tas?")
print('Mi nombre es', nombre, 'y tengo', edad, 'años')


print(f'mi nombre es {segundo_nombre}, y tengo {edad}, años y estamos en el año {2024+2}')